// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"github.com/jboelensns/openstack-cni/pkg/cniplugin"
	"sync"
)

// Ensure, that NetworkingMock does implement cniplugin.Networking.
// If this is not the case, regenerate this file with moq.
var _ cniplugin.Networking = &NetworkingMock{}

// NetworkingMock is a mock implementation of cniplugin.Networking.
//
//	func TestSomethingThatUsesNetworking(t *testing.T) {
//
//		// make and configure a mocked cniplugin.Networking
//		mockedNetworking := &NetworkingMock{
//			ConfigureFunc: func(namespace string, iface *cniplugin.NetworkInterface) error {
//				panic("mock out the Configure method")
//			},
//		}
//
//		// use mockedNetworking in code that requires cniplugin.Networking
//		// and then make assertions.
//
//	}
type NetworkingMock struct {
	// ConfigureFunc mocks the Configure method.
	ConfigureFunc func(namespace string, iface *cniplugin.NetworkInterface) error

	// calls tracks calls to the methods.
	calls struct {
		// Configure holds details about calls to the Configure method.
		Configure []struct {
			// Namespace is the namespace argument value.
			Namespace string
			// Iface is the iface argument value.
			Iface *cniplugin.NetworkInterface
		}
	}
	lockConfigure sync.RWMutex
}

// Configure calls ConfigureFunc.
func (mock *NetworkingMock) Configure(namespace string, iface *cniplugin.NetworkInterface) error {
	if mock.ConfigureFunc == nil {
		panic("NetworkingMock.ConfigureFunc: method is nil but Networking.Configure was just called")
	}
	callInfo := struct {
		Namespace string
		Iface     *cniplugin.NetworkInterface
	}{
		Namespace: namespace,
		Iface:     iface,
	}
	mock.lockConfigure.Lock()
	mock.calls.Configure = append(mock.calls.Configure, callInfo)
	mock.lockConfigure.Unlock()
	return mock.ConfigureFunc(namespace, iface)
}

// ConfigureCalls gets all the calls that were made to Configure.
// Check the length with:
//
//	len(mockedNetworking.ConfigureCalls())
func (mock *NetworkingMock) ConfigureCalls() []struct {
	Namespace string
	Iface     *cniplugin.NetworkInterface
} {
	var calls []struct {
		Namespace string
		Iface     *cniplugin.NetworkInterface
	}
	mock.lockConfigure.RLock()
	calls = mock.calls.Configure
	mock.lockConfigure.RUnlock()
	return calls
}
