---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: openstack-cni
  namespace: {{ .Values.cni.namespace }}
  labels:
    app.kubernetes.io/instance: openstack-cni
    app.kubernetes.io/name: openstack-cni
spec:
  selector:
    matchLabels:
      app: openstack-cni
  template:
    metadata:
      labels:
        app: openstack-cni
    spec:
      tolerations:
        - operator: Exists
          effect: NoSchedule
      hostNetwork: true
      containers:
      - name: openstack-cni
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: Always
        ports:
        - containerPort: 4242
          name: openstack-cni
          protocol: TCP
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        envFrom:
          - configMapRef:
              name: openstack-cni-config
          - secretRef:
              name: openstack-cni-secret
        volumeMounts:
        - mountPath: /host/opt/cni/bin
          name: cnibin
        - mountPath: /host/etc/cni
          name: cnietc
        - mountPath: /host/proc
          name: cniproc
      volumes:
      - hostPath:
          path: /opt/cni/bin
        name: cnibin
      - hostPath:
          path: /etc/cni
        name: cnietc
      - hostPath:
          path: /proc
        name: cniproc