---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "openstack-cni.fullname" . }}
  namespace: {{ .Values.cni.namespace }}
  labels:
    {{- include "openstack-cni.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "openstack-cni.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "openstack-cni.selectorLabels" . | nindent 8 }}
    spec:
      tolerations:
        - operator: Exists
          effect: NoSchedule
      hostNetwork: true
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: Always
        ports:
        - containerPort: 4242
          name: {{ .Chart.Name }}
          protocol: TCP
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        envFrom:
          - configMapRef:
              name: openstack-cni-config
          - secretRef:
              name: openstack-cni-secret
        volumeMounts:
        - mountPath: /host/opt/cni/bin
          name: cnibin
        - mountPath: /host/etc/cni
          name: cnietc
        - mountPath: /host/proc
          name: cniproc
      volumes:
      - hostPath:
          path: /opt/cni/bin
        name: cnibin
      - hostPath:
          path: /etc/cni
        name: cnietc
      - hostPath:
          path: /proc
        name: cniproc